version: "3"
services:
    svelte:
        build:
            context: ./
            dockerfile: Dockerfile
        environment:
            - API_URL=http://feedback.uib.no:5555
            - API_KEY=${API_KEY}
        command: node /app/__sapper__/build
        restart: unless-stopped
        ports:
            - 80:3000
